database:
  host: "localhost"
  port: 3306
  name: "mapsync"
  user: "root"
  password: "passwort"

settings:
  allow-public-download: false
  auto-upload-on-change: false
  auto-upload-enabled: false