name: MapSync
main: de.flattze.mapsync.MapSyncPlugin
version: 1.0
api-version: 1.20
commands:
  mapsync:
    description: Upload & Sync Maps
    usage: /mapsync <upload|mymaps>
    permission: mapsync.use