name: MapSync
version: 1.0
main: de.flattze.mapsync.MapSyncPlugin
api-version: 1.20
author: Flattze
commands:
  mapsync:
    description: Hauptbefehl für MapSync
    usage: /mapsync <upload|mymaps|...>

permissions:
  mapsync.admin:
    description: Erlaubt Adminfunktionen im Karten-GUI
    default: op
